#!/usr/bin/env python3
from __future__ import annotations

import argparse
import html
import json
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "catalog.json"
README = ROOT / "README.md"
INDEX = ROOT / "index.html"


TABLE_WIDTHS = {
    "surfaces": 3,
    "products": 4,
    "openforge_utilities": 5,
    "archived_specs": 5,
    "proof_trail": 2,
}


def validate_url(value: str, location: str) -> None:
    parsed = urlparse(value)
    if parsed.scheme != "https" or not parsed.netloc or parsed.username or parsed.password:
        raise ValueError(f"{location} must be an absolute credential-free HTTPS URL")


def validate_catalog(data: object) -> dict:
    if not isinstance(data, dict):
        raise ValueError("catalog root must be an object")
    required = ["organization", "surfaces", "products", "openforge_utilities", "archived_specs", "proof_trail"]
    missing = [key for key in required if key not in data]
    if missing:
        raise ValueError(f"catalog.json missing required keys: {', '.join(missing)}")
    if data.get("catalog_version") != "1.0.0":
        raise ValueError("catalog_version must be 1.0.0")
    organization = data["organization"]
    if not isinstance(organization, dict):
        raise ValueError("organization must be an object")
    for key in ("name", "tagline", "description"):
        if not isinstance(organization.get(key), str) or not organization[key].strip():
            raise ValueError(f"organization.{key} must be a non-empty string")
    for key, width in TABLE_WIDTHS.items():
        if not isinstance(data[key], list):
            raise ValueError(f"catalog.json key must be a list: {key}")
        if not data[key] and key != "products":
            raise ValueError(f"catalog.json key must be a non-empty list: {key}")
        names: set[str] = set()
        for row_number, row in enumerate(data[key], start=1):
            if not isinstance(row, list) or len(row) != width:
                raise ValueError(f"{key}[{row_number}] must contain exactly {width} strings")
            if any(not isinstance(cell, str) or not cell.strip() for cell in row):
                raise ValueError(f"{key}[{row_number}] must contain only non-empty strings")
            normalized_name = row[0].casefold()
            if normalized_name in names:
                raise ValueError(f"{key} contains duplicate name: {row[0]}")
            names.add(normalized_name)
            for column, cell in enumerate(row):
                if cell.startswith(("http://", "https://")):
                    validate_url(cell, f"{key}[{row_number}][{column}]")
    return data


def load_catalog(path: Path = CATALOG) -> dict:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return validate_catalog(data)
    except (OSError, json.JSONDecodeError, ValueError) as error:
        raise SystemExit(f"invalid catalog: {error}") from error


def md_link(label: str, url: str) -> str:
    return f"[{label}]({url})"


def render_readme(data: dict) -> str:
    org = data["organization"]
    lines = [
        "<!-- generated by scripts/generate_catalog.py; edit catalog.json instead -->",
        "",
        "<div align=\"center\">",
        "",
        f"# {org['name']}",
        "",
        f"**{org['tagline']}**",
        "",
        "[![Website](https://img.shields.io/badge/greyforge.tech-000000?style=for-the-badge&logo=vercel&logoColor=white)](https://greyforge.tech)",
        "[![GitHub](https://img.shields.io/badge/Open_Source-1f2937?style=for-the-badge&logo=github&logoColor=white)](https://github.com/GreyforgeLabs)",

        "",
        org["description"],
        "",
        "</div>",
        "",
        "---",
        "",
        "## What Greyforge Labs Is",
        "",
        "Greyforge Labs builds open-source desktop and operator tools. This GitHub catalog covers active OSS utilities and clearly labeled historical projects. See each repository for its source, license, documentation, and maintenance status.",
        "",
        "## Public Surfaces",
        "",
        "| Surface | Link | What Lives There |",
        "|---|---|---|",
    ]
    for name, url, desc in data["surfaces"]:
        lines.append(f"| {name} | {md_link(url.replace('https://', ''), url)} | {desc} |")
    lines.extend([
        "",
        "## Active Open-Source Tools",
        "",
        "| Project | Stack | Repo | Documentation | What It Does |",
        "|---|---|---|---|---|",
    ])
    for name, stack, repo, page, desc in data["openforge_utilities"]:
        lines.append(f"| {name} | {stack} | {md_link('GitHub', repo)} | {md_link('Docs', page)} | {desc} |")
    lines.extend([
        "",
        "## Historical Projects",
        "",
        "| Project | Stack | Repo | Documentation | Status |",
        "|---|---|---|---|---|",
    ])
    for name, stack, repo, page, status in data["archived_specs"]:
        lines.append(f"| {name} | {stack} | {md_link('GitHub', repo)} | {md_link('Docs', page)} | {status} |")
    lines.extend([
        "",
        "## Repository Records",
        "",
        "Use repository documentation and release records for project-specific claims:",
        "",
    ])
    for label, url in data["proof_trail"]:
        lines.append(f"- {md_link(label, url)}")
    lines.extend([
        "",
        "## Attribution",
        "",
        "Built by [Greyforge Labs](https://greyforge.tech/about). Individual authorship and license notices remain in each repository.",
        "",
        "<div align=\"center\">",
        "",
        "[greyforge.tech](https://greyforge.tech) - [GitHub](https://github.com/GreyforgeLabs)",
        "",
        f"**{org['tagline']}**",
        "",
        "</div>",
    ])
    return "\n".join(lines) + "\n"


def card(name: str, kicker: str, url: str, desc: str) -> str:
    return "\n".join([
        f'        <a class="card" href="{html.escape(url)}">',
        f"          <span class=\"card-kicker\">{html.escape(kicker)}</span>",
        f"          <h3>{html.escape(name)}</h3>",
        f"          <p>{html.escape(desc)}</p>",
        "        </a>",
    ])


def render_index(data: dict) -> str:
    org = data["organization"]
    product_cards = "\n".join(card(name, kicker, url, desc) for name, kicker, url, desc in data["products"])
    product_section = f"""
    <section class="section" aria-labelledby="products-title">
      <div class="section-heading">
        <p class="eyebrow">Catalog</p>
        <h2 id="products-title">Products</h2>
      </div>
      <div class="card-grid product-grid">
{product_cards}
      </div>
    </section>
""" if data["products"] else ""
    repo_links = "\n".join(
        f'        <a href="{html.escape(repo)}"><strong>{html.escape(name)}</strong><span>{html.escape(desc)}</span></a>'
        for name, _stack, repo, _page, desc in data["openforge_utilities"]
    )
    archive_links = "\n".join(
        f'        <a href="{html.escape(repo)}"><strong>{html.escape(name)}</strong><span>{html.escape(status.replace("`", ""))}</span></a>'
        for name, _stack, repo, _page, status in data["archived_specs"]
    )
    proof_links = "\n".join(
        f'        <a href="{html.escape(url)}">{html.escape(label)}</a>' for label, url in data["proof_trail"]
    )
    return f"""<!doctype html>
<!-- generated by scripts/generate_catalog.py; edit catalog.json instead -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Greyforge Labs on GitHub | Open-Source Tools and Historical Projects</title>
  <meta name="description" content="{html.escape(org['description'])}">
  <meta name="robots" content="index,follow">
  <link rel="canonical" href="https://greyforge.tech/">
  <meta property="og:type" content="website">
  <meta property="og:title" content="Greyforge Labs on GitHub">
  <meta property="og:description" content="{html.escape(org['description'])}">
  <meta property="og:url" content="https://greyforgelabs.github.io/Greyforgelabs/">
  <meta property="og:image" content="https://avatars.githubusercontent.com/u/252855775?v=4">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="Greyforge Labs on GitHub">
  <meta name="twitter:description" content="{html.escape(org['description'])}">
  <meta name="theme-color" content="#0b0f14">
  <link rel="stylesheet" href="./assets/github-page.css">
  <script type="application/ld+json">
  {{
    "@context": "https://schema.org",
    "@type": "Organization",
    "name": "Greyforge Labs",
    "url": "https://greyforge.tech",
    "logo": "https://avatars.githubusercontent.com/u/252855775?v=4",
    "sameAs": [
      "https://github.com/GreyforgeLabs"
    ],
    "knowsAbout": [
      "open source utilities",
      "Linux desktop tools",
      "operator tools",
      "developer tooling"
    ]
  }}
  </script>
</head>
<body>
  <header class="site-header">
    <a class="brand-link" href="https://greyforge.tech" aria-label="Greyforge Labs">
      <img src="https://avatars.githubusercontent.com/u/252855775?v=4" alt="Greyforge Labs mark" width="48" height="48">
      <span>Greyforge Labs</span>
    </a>
    <nav aria-label="Primary">
      <a href="#openforge-title">Open Source</a>
      <a href="#archive-title">History</a>
      <a href="https://github.com/GreyforgeLabs">GitHub</a>
    </nav>
  </header>

  <main>
    <section class="hero" aria-labelledby="hero-title">
      <div class="hero-copy">
        <p class="eyebrow">Open-source catalog</p>
        <h1 id="hero-title">Greyforge Labs</h1>
        <p class="tagline">Autonomy, Engineered.</p>
        <p class="hero-text">
          {html.escape(org['description'])}
        </p>
        <div class="hero-actions" aria-label="Main links">
          <a class="button primary" href="https://greyforge.tech">Visit Greyforge</a>
          <a class="button" href="https://github.com/GreyforgeLabs">GitHub Repos</a>
          <a class="button" href="#openforge-title">Explore Tools</a>
        </div>
      </div>
      <aside class="hero-panel" aria-label="Surface map">
        <span>Open Source</span>
        <strong>Desktop and operator tools</strong>
        <span>History</span>
        <strong>Sley legacy and archival projects</strong>
        <span>Documentation</span>
        <strong>Repository records</strong>
        <span>GitHub</span>
        <strong>Repos and releases</strong>
      </aside>
    </section>

{product_section}
    <section class="section" aria-labelledby="openforge-title">
      <div class="section-heading">
        <p class="eyebrow">Open Source</p>
        <h2 id="openforge-title">Active Open-Source Tools</h2>
      </div>
      <div class="repo-list">
{repo_links}
      </div>
    </section>

    <section class="section" aria-labelledby="archive-title">
      <div class="section-heading">
        <p class="eyebrow">Archive</p>
        <h2 id="archive-title">Historical Projects</h2>
      </div>
      <div class="repo-list archive-list">
{archive_links}
      </div>
    </section>

    <section class="section proof" aria-labelledby="proof-title">
      <div class="section-heading">
        <p class="eyebrow">Source and documentation</p>
        <h2 id="proof-title">Repository Records</h2>
      </div>
      <div class="link-row">
{proof_links}
      </div>
    </section>
  </main>

  <footer>
    <span>Built by Greyforge Labs. Individual authorship and license notices remain in each repository.</span>
    <nav aria-label="Footer">
      <a href="https://greyforge.tech">greyforge.tech</a>
      <a href="https://github.com/GreyforgeLabs">GitHub</a>
    </nav>
  </footer>
</body>
</html>
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="rewrite generated files")
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    if args.write == args.check:
        raise SystemExit("choose exactly one of --write or --check")

    data = load_catalog()
    expected = {README: render_readme(data), INDEX: render_index(data)}
    if args.write:
        for path, content in expected.items():
            path.write_text(content, encoding="utf-8")
        return

    stale = [str(path.relative_to(ROOT)) for path, content in expected.items() if path.read_text(encoding="utf-8") != content]
    if stale:
        raise SystemExit("generated files are stale: " + ", ".join(stale))


if __name__ == "__main__":
    main()
